[package]
name = "ton_liteapi"
version = "0.1.0"
edition = "2021"

[dependencies]
adnl = { version = "0.1.0", features = ["std", "dalek"] }
x25519-dalek = "2.0.0-pre.1"
curve25519-dalek = "4.0.0-pre.2"
rand = "0.8.5"
tl-proto = "0.4.2"
derivative = "2.2.0"
ciborium-io = "0.2.0"
log = '0.4.14'
hex = "0.4.3"